### ISSUE TITLE
Gen 1 Articuno, Zapdos, Moltres, Mew Error

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1032]
#When legality checking a Gen 1 Articuno, Zapdos, Moltres, or Mew the following error persists. 
Invalid: Internal Error.

CTRL+Click on Current Moves yields this error.

Exception Details:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.Core.Legal.getValidMoves(PKM pkm, GameVersion Version, IReadOnlyList`1 vs, Boolean LVL, Boolean Relearn, Boolean Tutor, Boolean Machine, Boolean MoveReminder, Boolean RemoveTransferHM)
   at PKHeX.Core.LegalityAnalysis.getSuggestedMoves(Boolean tm, Boolean tutor, Boolean reminder)
   at PKHeX.WinForms.Main.clickMoves(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.GroupBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.2719, Culture=neutral, PublicKeyToken=null
C:\[REDACTED]\PKHeX\2719.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.2719, Culture=neutral, PublicKeyToken=null
C:\[REDACTED]\PKHeX\PKHeX.Core.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```
Thanks you for all your work! And for reading!

**Comment by PrometheusG** [comment]
It also exists in _eevee, gyarados, pikachu, kadabra, blastoise_ in my VC Blue game
In Gen 7 .SAV file the last 4 pokemon I mentioned (all except eevee,which I haven't transfered with pokebank yet) show the exact same error as Gen1 .SAV file and as greenDarkness mentioned.

I used PKHeX Build 2716 (2719 will have no difference I suppose)

**Comment by wwwwwwzx** [comment]
It's my fault, I change the default `Moves` for `Encounterstatic` to null for saving memory
Change [this line](https://github.com/kwsch/PKHeX/blob/master/PKHeX/Legality/Core.cs#L1123) to 
> var special = s?.FirstOrDefault(m => m.Moves != null && m.Moves[0] != 0 && pkm.Moves.Contains(m.Moves[0])); will solve the problem
