### ISSUE TITLE
Crystal - impossible to export save

### ISSUE THREAD

**Issue by ewormPL** [kwsch/PKHeX#1038]
Trying to save VC Crystal's sav.dat results in an error as seen below:

```
Exception Details:
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at PKHeX.WinForms.Main.validateComboBox(Object sender)
   at PKHeX.WinForms.Main.validateComboBox(Object sender, CancelEventArgs e)
   at System.Windows.Forms.Control.OnValidating(CancelEventArgs e)
   at System.Windows.Forms.ComboBox.OnValidating(CancelEventArgs e)
   at System.Windows.Forms.Control.NotifyValidating()
   at System.Windows.Forms.Control.PerformControlValidation(Boolean bulkValidation)
   at System.Windows.Forms.Control.PerformContainerValidation(ValidationConstraints validationConstraints)
   at System.Windows.Forms.Control.PerformContainerValidation(ValidationConstraints validationConstraints)
   at System.Windows.Forms.Control.PerformContainerValidation(ValidationConstraints validationConstraints)
   at System.Windows.Forms.Control.PerformContainerValidation(ValidationConstraints validationConstraints)
   at System.Windows.Forms.Control.PerformContainerValidation(ValidationConstraints validationConstraints)
   at System.Windows.Forms.ContainerControl.ValidateChildren(ValidationConstraints validationConstraints)
   at System.Windows.Forms.Form.ValidateChildren(ValidationConstraints validationConstraints)
   at System.Windows.Forms.Form.ValidateChildren()
   at PKHeX.WinForms.Main.clickExportSAV(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
W:\Games\PKHeX\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=pl, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_pl_b77a5c561934e089\System.Windows.Forms.resources.dll

mscorlib.resources, Version=4.0.0.0, Culture=pl, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_pl_b77a5c561934e089\mscorlib.resources.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```

Any idea of what causes it? It happens even when I open the sav.dat and then immediately try to save it without editing anything.

**Comment by ReignOfComputer** [comment]
Could not reproduce. Could you upload the save somewhere?

**Comment by ewormPL** [comment]
[Here it is](http://prismtower.net16.net/crystalfailsav.dat).

**Comment by ReignOfComputer** [comment]
Could not reproduce on latest commit.

**Comment by ewormPL** [comment]
I'm using the March 18th version from Project Pokémon. I tried compiling the latest commit with MSBuild, but got an error about "no output destination" or something. Is there any way I could download the exe of the latest commit to try - or can you recommend a simple but working way of compiling it?

**Comment by ReignOfComputer** [comment]
Yep, just grab the latest commit from https://teamcity.projectpokemon.org/viewLog.html?buildId=5524&buildTypeId=PKHeX_BuildWindows&tab=artifacts (click login as guest).

**Comment by ewormPL** [comment]
The problem's indeed gone on the latest commit, thanks a bunch.
Incidentally, is that link always gonna lead me to a downloadable exe version of the latest PKHeX or just to this one? Because that's really useful.

**Comment by ReignOfComputer** [comment]
In the commit list at https://github.com/kwsch/PKHeX/commits/master, click the green tick on the latest commit, then Details of "Build - Windows", log in as guest, Artifacts tab. There used to be a shortcut url but that doesn't seem to be working anymore after teamcity moved.

@evandixon

**Comment by ewormPL** [comment]
Thanks a lot.

**Comment by evandixon** [comment]
Here's the permalink: https://teamcity.projectpokemon.org/viewLog.html?buildTypeId=PKHeX_BuildWindows&buildId=lastSuccessful&buildBranch=%3Cdefault%3E

The short version went away after I changed hosting providers, and I never brought it back.
