### ISSUE TITLE
Emerald Pokédex uneditable

### ISSUE THREAD

**Issue by ewormPL** [kwsch/PKHeX#1101]
Can't edit the Pokédex in my Emerald save for whatever reason. I'm using the newest build (2949) and getting the following error:

```
Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PKHeX.Core.SAV3.setSeen(Int32 species, Boolean seen) in D:\TeamCity\BuildAgentPPOrg\work\3a4b40ceb1c3e268\PKHeX\Saves\SAV3.cs:line 542
   at PKHeX.WinForms.SAV_SimplePokedex.B_Save_Click(Object sender, EventArgs e) in D:\TeamCity\BuildAgentPPOrg\work\3a4b40ceb1c3e268\PKHeX.WinForms\Subforms\Save Editors\SAV_SimplePokedex.cs:line 40
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.2949, Culture=neutral, PublicKeyToken=null
W:\Games\PKHeX\PKHeX Build 2949\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.2949, Culture=neutral, PublicKeyToken=null
W:\Games\PKHeX\PKHeX Build 2949\PKHeX.Core.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```

Also, importing pk files into the save doesn't modify the dex by default, which I believe should be the case and used to be the case?

**Comment by kwsch** [comment]
Will need to see the save file; I'm not experiencing this on any of my emerald saves.

**Comment by ewormPL** [comment]
[Here it is](http://prismtower.net16.net/emeraldfail.sav)
The save comes from a VC inject version and it has a bunch of modified mons from Gen II put in. Still, I can't imagine why those wouldn't interfere with the sav, yet changing the Pokédex is a no-no?

**Comment by kwsch** [comment]
Webpage is inaccessible, just zip -> drop into this page :)

**Comment by sora10pls** [comment]
I was able to access the webpage, here's the save:
[emeraldfail.zip](https://github.com/kwsch/PKHeX/files/965790/emeraldfail.zip)

**Comment by kwsch** [comment]
Block 4 is not present in the save file; I'll implement a workaround to not write to that block if it's not there.

**Comment by greenDarkness** [comment]
I realize that this change was already made, but do we know if that save file is playable? In my experience when PKHeX didn't read my save, is was because the extracted save was not a 1;1 copy; or the save was corrupt.
