### ISSUE TITLE
Error on Build 3254

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1173]
Got then error when I viewed a Sudowoodo that was flagged as illegal, but when viewed it was legal. I can provide the PK7 if necessary.

```
Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.WinForms.Controls.PKMEditor.updateLegality(LegalityAnalysis la, Boolean skipMoveRepop) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX.WinForms\Controls\PKM Editor\PKMEditor.cs:line 255
   at PKHeX.WinForms.Controls.PKMEditor.populateFields(PKM pk, Boolean focus) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX.WinForms\Controls\PKM Editor\PKMEditor.cs:line 234
   at PKHeX.WinForms.Controls.ContextMenuSAV.ClickView(Object sender, EventArgs e) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX.WinForms\Controls\SAV Editor\ContextMenuSAV.cs:line 33
   at PKHeX.WinForms.Controls.ContextMenuSAV.OmniClick(Object sender, EventArgs e, Keys z) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX.WinForms\Controls\SAV Editor\ContextMenuSAV.cs:line 20
   at PKHeX.WinForms.Controls.SAVEditor.clickSlot(Object sender, EventArgs e) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX.WinForms\Controls\SAV Editor\SAVEditor.cs:line 301
   at PKHeX.WinForms.Controls.BoxEditor.pbBoxSlot_MouseClick(Object sender, MouseEventArgs e) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX.WinForms\Controls\SAV Editor\BoxEditor.cs:line 187
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by kwsch** [comment]
please provide pk7 :)

**Comment by greenDarkness** [comment]
Did you get it, or do I still need to provide the pk7? ^_^

**Comment by kwsch** [comment]
Was able to figure it out 🌵
