### ISSUE TITLE
Opening Misc Tab in Diamond or Pearl throws exception error

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#1447]
Whenever I try to open the misc tab in my Pokemon Diamond or Pearl Save, it just throws this error:
![error pic 3](https://user-images.githubusercontent.com/20786416/30149735-08849f0a-9366-11e7-809e-d15d4a88a353.png)

And the Inside of the dialog box shows this:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '255' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at PKHeX.WinForms.SAV_Misc4.ReadPoketch() in C:\Users\Alec\Desktop\3DS Editing\PKHeX-master\PKHeX.WinForms\Subforms\Save Editors\Gen4\SAV_Misc4.cs:line 192
   at PKHeX.WinForms.SAV_Misc4.ReadMain() in C:\Users\Alec\Desktop\3DS Editing\PKHeX-master\PKHeX.WinForms\Subforms\Save Editors\Gen4\SAV_Misc4.cs:line 129
   at PKHeX.WinForms.SAV_Misc4..ctor(SaveFile sav) in C:\Users\Alec\Desktop\3DS Editing\PKHeX-master\PKHeX.WinForms\Subforms\Save Editors\Gen4\SAV_Misc4.cs:line 73
   at PKHeX.WinForms.Controls.SAVEditor.B_OpenMiscEditor_Click(Object sender, EventArgs e) in C:\Users\Alec\Desktop\3DS Editing\PKHeX-master\PKHeX.WinForms\Controls\SAV Editor\SAVEditor.cs:line 595
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PKHeX
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alec/Desktop/3DS%20Editing/PKHeX-master/PKHeX.WinForms/bin/Debug/PKHeX.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PKHeX.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alec/Desktop/3DS%20Editing/PKHeX-master/PKHeX.WinForms/bin/Debug/PKHeX.Core.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by kwsch** [comment]
Have you not received the Poketch yet?

**Comment by architdate** [comment]
Cant replicate the issue with a save file i found online.

**Comment by architdate** [comment]
Tried with a completely new save file. Got the same exception 
![image](https://user-images.githubusercontent.com/17220860/30171884-b87fc73a-9425-11e7-8760-c39068c8d4c6.png)
I think a poketch check needs to be implemented. I'll try sending a PR to fix this when am free @kwsch
