### ISSUE TITLE
PkHex Throws Exception Error when I try to access the Underground tab

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#1449]
Whenever I try to open the Undreground tab, it just throws an exception error which will be shown below. Doing some experiementation, it seems that having any of the records above 100 will cause the error to occur, with the program claiming that the value exceeds the maximum. However, the in-game maximum is far higher than the program's artificial 100 limit.

How to replicate: Set one of the Underground values to 100, save and then open the game and increment that value in-game. Such as setting spheres to 100 and then mining one more sphere so that your in-game spheres collected is 101+. Save and reopen PKHeX, and try to open the underground tab and you'll get the following errors

![error pic 4](https://user-images.githubusercontent.com/20786416/30200507-757727c6-9434-11e7-9cfe-b25a5b6346e2.png)

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '305' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at PKHeX.WinForms.SAV_Underground.GetUGScores() in C:\Users\Alec\Desktop\3DS Editing\PKHeX-master\PKHeX.WinForms\Subforms\Save Editors\Gen4\SAV_Underground.cs:line 25
   at PKHeX.WinForms.SAV_Underground..ctor(SaveFile sav) in C:\Users\Alec\Desktop\3DS Editing\PKHeX-master\PKHeX.WinForms\Subforms\Save Editors\Gen4\SAV_Underground.cs:line 18
   at PKHeX.WinForms.Controls.SAVEditor.B_OpenUGSEditor_Click(Object sender, EventArgs e) in C:\Users\Alec\Desktop\3DS Editing\PKHeX-master\PKHeX.WinForms\Controls\SAV Editor\SAVEditor.cs:line 1109
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PKHeX
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alec/Desktop/3DS%20Editing/PKHeX-master/PKHeX.WinForms/bin/Debug/PKHeX.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PKHeX.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alec/Desktop/3DS%20Editing/PKHeX-master/PKHeX.WinForms/bin/Debug/PKHeX.Core.DLL
----------------------------------------

**Comment by architdate** [comment]
Is there documentation on the actual limit?

**Comment by kwsch** [comment]
most values are uncapped, if it's being read/written as an int32 then it should be capped as such

im pretty sure that these are a subset of the trainer stat records (see gen6/7's presentation)
