### ISSUE TITLE
Newest release incompatible with Linux

### ISSUE THREAD

**Issue by Zekario** [kwsch/PKHeX#151]
Before I could run the exe with mono (although it crashed every time I hit Super/Windows key), and before that I could run it flawlessly with WINE. Now, both WINE and mono fail.

With mono, here is what I get:

```
Unhandled Exception:
System.NotImplementedException: The method or operation is not implemented.
  at System.Linq.Enumerable+Iterator`1[TSource].System.Collections.IEnumerator.Reset () <0x419003a0 + 0x0001b> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.GetListFromEnumerable (IEnumerable enumerable) <0x418ff7a0 + 0x001e8> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.ResetList () <0x418fbba0 + 0x0051b> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource..ctor (System.Object dataSource, System.String dataMember) <0x418fba40 + 0x00103> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.BindingSource:.ctor (object,string)
  at PKHeX.Main.populateFilteredDataSources () <0x418fe310 + 0x002fb> in <filename unknown>:0 
  at PKHeX.Main.InitializeLanguage () <0x418ea480 + 0x00773> in <filename unknown>:0 
  at PKHeX.Main.changeMainLanguage (System.Object sender, System.EventArgs e) <0x418e73b0 + 0x000ab> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged (System.EventArgs e) <0x418e7320 + 0x00065> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged (System.Object sender, System.EventArgs e) <0x418e72f0 + 0x0001b> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.OnSelectedIndexChanged (System.EventArgs e) <0x418c8720 + 0x00073> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.SetSelectedIndex (Int32 value, Boolean supressAutoScroll) <0x418c84d0 + 0x00129> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.set_SelectedIndex (Int32 value) <0x418c84a0 + 0x00013> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex (Int32 value) <0x418e7260 + 0x00026> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripComboBox:set_SelectedIndex (int)
  at PKHeX.Main..ctor () <0x417eb1a0 + 0x0250f> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () <0x41789d90 + 0x0002f> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: The method or operation is not implemented.
  at System.Linq.Enumerable+Iterator`1[TSource].System.Collections.IEnumerator.Reset () <0x419003a0 + 0x0001b> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.GetListFromEnumerable (IEnumerable enumerable) <0x418ff7a0 + 0x001e8> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.ResetList () <0x418fbba0 + 0x0051b> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource..ctor (System.Object dataSource, System.String dataMember) <0x418fba40 + 0x00103> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.BindingSource:.ctor (object,string)
  at PKHeX.Main.populateFilteredDataSources () <0x418fe310 + 0x002fb> in <filename unknown>:0 
  at PKHeX.Main.InitializeLanguage () <0x418ea480 + 0x00773> in <filename unknown>:0 
  at PKHeX.Main.changeMainLanguage (System.Object sender, System.EventArgs e) <0x418e73b0 + 0x000ab> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged (System.EventArgs e) <0x418e7320 + 0x00065> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged (System.Object sender, System.EventArgs e) <0x418e72f0 + 0x0001b> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.OnSelectedIndexChanged (System.EventArgs e) <0x418c8720 + 0x00073> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.SetSelectedIndex (Int32 value, Boolean supressAutoScroll) <0x418c84d0 + 0x00129> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.set_SelectedIndex (Int32 value) <0x418c84a0 + 0x00013> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex (Int32 value) <0x418e7260 + 0x00026> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripComboBox:set_SelectedIndex (int)
  at PKHeX.Main..ctor () <0x417eb1a0 + 0x0250f> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () <0x41789d90 + 0x0002f> in <filename unknown>:0
```

With WINE, I get this:

```
Unhandled Exception:
System.NotImplementedException: The method or operation is not implemented.
  at System.Linq.Enumerable+Iterator\`1[TSource].System.Collections.IEnumerator.Reset () <0xd944420 + 0x0001f> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.GetListFromEnumerable (IEnumerable enumerable) <0xd943330 + 0x00199> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.ResetList () <0xd940548 + 0x003ff> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource..ctor (System.Object dataSource, System.String dataMember) <0xd940458 + 0x000b7> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.BindingSource:.ctor (object,string)
  at PKHeX.Main.populateFilteredDataSources () <0xd942410 + 0x00273> in <filename unknown>:0 
  at PKHeX.Main.InitializeLanguage () <0xd91d6d0 + 0x00713> in <filename unknown>:0 
  at PKHeX.Main.changeMainLanguage (System.Object sender, System.EventArgs e) <0xd91b130 + 0x000a3> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged (System.EventArgs e) <0xd91b0c0 + 0x00056> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged (System.Object sender, System.EventArgs e) <0xd91b0a0 + 0x0001a> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.OnSelectedIndexChanged (System.EventArgs e) <0xd913ff8 + 0x0006a> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.SetSelectedIndex (Int32 value, Boolean supressAutoScroll) <0xd913dc8 + 0x00129> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.set_SelectedIndex (Int32 value) <0xd913d98 + 0x0001f> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex (Int32 value) <0xd91b020 + 0x00025> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripComboBox:set_SelectedIndex (int)
  at PKHeX.Main..ctor () <0x228aa80 + 0x02007> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () <0x2220fa8 + 0x00033> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: The method or operation is not implemented.
  at System.Linq.Enumerable+Iterator\`1[TSource].System.Collections.IEnumerator.Reset () <0xd944420 + 0x0001f> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.GetListFromEnumerable (IEnumerable enumerable) <0xd943330 + 0x00199> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.ResetList () <0xd940548 + 0x003ff> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource..ctor (System.Object dataSource, System.String dataMember) <0xd940458 + 0x000b7> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.BindingSource:.ctor (object,string)
  at PKHeX.Main.populateFilteredDataSources () <0xd942410 + 0x00273> in <filename unknown>:0 
  at PKHeX.Main.InitializeLanguage () <0xd91d6d0 + 0x00713> in <filename unknown>:0 
  at PKHeX.Main.changeMainLanguage (System.Object sender, System.EventArgs e) <0xd91b130 + 0x000a3> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged (System.EventArgs e) <0xd91b0c0 + 0x00056> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged (System.Object sender, System.EventArgs e) <0xd91b0a0 + 0x0001a> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.OnSelectedIndexChanged (System.EventArgs e) <0xd913ff8 + 0x0006a> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.SetSelectedIndex (Int32 value, Boolean supressAutoScroll) <0xd913dc8 + 0x00129> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.set_SelectedIndex (Int32 value) <0xd913d98 + 0x0001f> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex (Int32 value) <0xd91b020 + 0x00025> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripComboBox:set_SelectedIndex (int)
  at PKHeX.Main..ctor () <0x228aa80 + 0x02007> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () <0x2220fa8 + 0x00033> in <filename unknown>:0 
```

**Comment by kwsch** [comment]
Appears to be in the populateFilteredDataSources method, related to BindingSource and LINQ enumerables. Maybe it's due to the foreach loop?

http://stackoverflow.com/questions/3947786/when-ienumerator-reset-method-is-called

Please try the following exe ([link] (https://dl.dropboxusercontent.com/u/12206225/pporg/PKHeX/PKHeX%20(fix072816).zip))
 which has the above fix.

**Comment by Zekario** [comment]
Sorry for not responding, I just noticed this.

With WINE, running that new exe, I get:

```

Unhandled Exception:
System.NotImplementedException: The method or operation is not implemented.
  at System.Linq.Enumerable+Iterator`1[TSource].System.Collections.IEnumerator.Reset () <0xd944448 + 0x0001f> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.GetListFromEnumerable (IEnumerable enumerable) <0xd943358 + 0x00199> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.ResetList () <0xd940548 + 0x003ff> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource..ctor (System.Object dataSource, System.String dataMember) <0xd940458 + 0x000b7> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.BindingSource:.ctor (object,string)
  at PKHeX.Main.populateFilteredDataSources () <0xd942410 + 0x00277> in <filename unknown>:0 
  at PKHeX.Main.InitializeLanguage () <0xd91d6d0 + 0x00713> in <filename unknown>:0 
  at PKHeX.Main.changeMainLanguage (System.Object sender, System.EventArgs e) <0xd91b130 + 0x000a3> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged (System.EventArgs e) <0xd91b0c0 + 0x00056> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged (System.Object sender, System.EventArgs e) <0xd91b0a0 + 0x0001a> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.OnSelectedIndexChanged (System.EventArgs e) <0xd913ff8 + 0x0006a> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.SetSelectedIndex (Int32 value, Boolean supressAutoScroll) <0xd913dc8 + 0x00129> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.set_SelectedIndex (Int32 value) <0xd913d98 + 0x0001f> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex (Int32 value) <0xd91b020 + 0x00025> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripComboBox:set_SelectedIndex (int)
  at PKHeX.Main..ctor () <0x228aa80 + 0x02007> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () <0x2220fa8 + 0x00033> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: The method or operation is not implemented.
  at System.Linq.Enumerable+Iterator`1[TSource].System.Collections.IEnumerator.Reset () <0xd944448 + 0x0001f> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.GetListFromEnumerable (IEnumerable enumerable) <0xd943358 + 0x00199> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.ResetList () <0xd940548 + 0x003ff> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource..ctor (System.Object dataSource, System.String dataMember) <0xd940458 + 0x000b7> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.BindingSource:.ctor (object,string)
  at PKHeX.Main.populateFilteredDataSources () <0xd942410 + 0x00277> in <filename unknown>:0 
  at PKHeX.Main.InitializeLanguage () <0xd91d6d0 + 0x00713> in <filename unknown>:0 
  at PKHeX.Main.changeMainLanguage (System.Object sender, System.EventArgs e) <0xd91b130 + 0x000a3> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged (System.EventArgs e) <0xd91b0c0 + 0x00056> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged (System.Object sender, System.EventArgs e) <0xd91b0a0 + 0x0001a> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.OnSelectedIndexChanged (System.EventArgs e) <0xd913ff8 + 0x0006a> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.SetSelectedIndex (Int32 value, Boolean supressAutoScroll) <0xd913dc8 + 0x00129> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.set_SelectedIndex (Int32 value) <0xd913d98 + 0x0001f> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex (Int32 value) <0xd91b020 + 0x00025> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripComboBox:set_SelectedIndex (int)
  at PKHeX.Main..ctor () <0x228aa80 + 0x02007> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () <0x2220fa8 + 0x00033> in <filename unknown>:0 

```

Mono gives me:

```

Unhandled Exception:
System.NotImplementedException: The method or operation is not implemented.
  at System.Linq.Enumerable+Iterator`1[TSource].System.Collections.IEnumerator.Reset () <0x407743a0 + 0x0001b> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.GetListFromEnumerable (IEnumerable enumerable) <0x407737a0 + 0x001e8> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.ResetList () <0x4076fac0 + 0x0051b> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource..ctor (System.Object dataSource, System.String dataMember) <0x4076f960 + 0x00103> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.BindingSource:.ctor (object,string)
  at PKHeX.Main.populateFilteredDataSources () <0x40772290 + 0x002f7> in <filename unknown>:0 
  at PKHeX.Main.InitializeLanguage () <0x4075e290 + 0x00773> in <filename unknown>:0 
  at PKHeX.Main.changeMainLanguage (System.Object sender, System.EventArgs e) <0x4075b1c0 + 0x000ab> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged (System.EventArgs e) <0x4075b130 + 0x00065> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged (System.Object sender, System.EventArgs e) <0x4075b100 + 0x0001b> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.OnSelectedIndexChanged (System.EventArgs e) <0x4073c540 + 0x00073> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.SetSelectedIndex (Int32 value, Boolean supressAutoScroll) <0x4073c2f0 + 0x00129> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.set_SelectedIndex (Int32 value) <0x4073c2c0 + 0x00013> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex (Int32 value) <0x4075b070 + 0x00026> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripComboBox:set_SelectedIndex (int)
  at PKHeX.Main..ctor () <0x4065f1a0 + 0x0250f> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () <0x405fdd90 + 0x0002f> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: The method or operation is not implemented.
  at System.Linq.Enumerable+Iterator`1[TSource].System.Collections.IEnumerator.Reset () <0x407743a0 + 0x0001b> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.GetListFromEnumerable (IEnumerable enumerable) <0x407737a0 + 0x001e8> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource.ResetList () <0x4076fac0 + 0x0051b> in <filename unknown>:0 
  at System.Windows.Forms.BindingSource..ctor (System.Object dataSource, System.String dataMember) <0x4076f960 + 0x00103> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.BindingSource:.ctor (object,string)
  at PKHeX.Main.populateFilteredDataSources () <0x40772290 + 0x002f7> in <filename unknown>:0 
  at PKHeX.Main.InitializeLanguage () <0x4075e290 + 0x00773> in <filename unknown>:0 
  at PKHeX.Main.changeMainLanguage (System.Object sender, System.EventArgs e) <0x4075b1c0 + 0x000ab> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged (System.EventArgs e) <0x4075b130 + 0x00065> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged (System.Object sender, System.EventArgs e) <0x4075b100 + 0x0001b> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.OnSelectedIndexChanged (System.EventArgs e) <0x4073c540 + 0x00073> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.SetSelectedIndex (Int32 value, Boolean supressAutoScroll) <0x4073c2f0 + 0x00129> in <filename unknown>:0 
  at System.Windows.Forms.ComboBox.set_SelectedIndex (Int32 value) <0x4073c2c0 + 0x00013> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex (Int32 value) <0x4075b070 + 0x00026> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripComboBox:set_SelectedIndex (int)
  at PKHeX.Main..ctor () <0x4065f1a0 + 0x0250f> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () <0x405fdd90 + 0x0002f> in <filename unknown>:0 

```

It seems to be the same thing to me, at first glance.

**Comment by evandixon** [comment]
https://social.msdn.microsoft.com/Forums/vstudio/en-US/0573134c-ba0b-4161-a3f6-7aecde6b2950/linq-notimplementedexception?forum=csharpgeneral

Perhaps adding ".ToList()" to the end of the ".Where(...)" statements would resolve the issue?

**Comment by kwsch** [comment]
@Zekario , please try the [latest exe](https://dl.dropboxusercontent.com/u/12206225/pporg/PKHeX/PKHeX%20(fix07-30-16).zip) with above commit.

**Comment by Zekario** [comment]
WINE:

```

Unhandled Exception:
System.UriFormatException: Invalid URI: The URI scheme is not valid.
  at System.Uri.Parse (UriKind kind, System.String uriString) <0x63b3d80 + 0x00097> in <filename unknown>:0 
  at System.Uri.ParseUri (UriKind kind) <0x63b3cb0 + 0x0001f> in <filename unknown>:0 
  at System.Uri..ctor (System.String uriString, Boolean dontEscape) <0x63b3b18 + 0x00113> in <filename unknown>:0 
  at System.Uri..ctor (System.String uriString) <0x63b3ae8 + 0x0001f> in <filename unknown>:0 
  at PKHeX.Util.NormalizePath (System.String path) <0x63b2cf8 + 0x0004f> in <filename unknown>:0 
  at PKHeX.Main.detectSaveFile () <0x63b20b8 + 0x0046f> in <filename unknown>:0 
  at PKHeX.Main..ctor () <0x228aad0 + 0x0222b> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () <0x2220fa8 + 0x00033> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.UriFormatException: Invalid URI: The URI scheme is not valid.
  at System.Uri.Parse (UriKind kind, System.String uriString) <0x63b3d80 + 0x00097> in <filename unknown>:0 
  at System.Uri.ParseUri (UriKind kind) <0x63b3cb0 + 0x0001f> in <filename unknown>:0 
  at System.Uri..ctor (System.String uriString, Boolean dontEscape) <0x63b3b18 + 0x00113> in <filename unknown>:0 
  at System.Uri..ctor (System.String uriString) <0x63b3ae8 + 0x0001f> in <filename unknown>:0 
  at PKHeX.Util.NormalizePath (System.String path) <0x63b2cf8 + 0x0004f> in <filename unknown>:0 
  at PKHeX.Main.detectSaveFile () <0x63b20b8 + 0x0046f> in <filename unknown>:0 
  at PKHeX.Main..ctor () <0x228aad0 + 0x0222b> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) PKHeX.Main:.ctor ()
  at PKHeX.Program.Main () <0x2220fa8 + 0x00033> in <filename unknown>:0 

```

Using mono seems to work like before, I can use it but pressing super/windows key makes it crash with this:

```

Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Windows.Forms.X11Keyboard.Xutf8LookupString (intptr,System.Windows.Forms.XEvent&,byte[],int,intptr&,System.Windows.Forms.XLookupStatus&) <0x000a4>
  at System.Windows.Forms.X11Keyboard.LookupString (System.Windows.Forms.XEvent&,int,System.Windows.Forms.XKeySym&,System.Windows.Forms.XLookupStatus&) <0x000c3>
  at System.Windows.Forms.X11Keyboard.EventToVkey (System.Windows.Forms.XEvent) <0x0003f>
  at System.Windows.Forms.X11Keyboard.ToUnicode (int,int,string&) <0x0035f>
  at System.Windows.Forms.X11Keyboard.TranslateMessage (System.Windows.Forms.MSG&) <0x00127>
  at System.Windows.Forms.XplatUIX11.TranslateMessage (System.Windows.Forms.MSG&) <0x00023>
  at System.Windows.Forms.XplatUI.TranslateMessage (System.Windows.Forms.MSG&) <0x0001f>
  at System.Windows.Forms.Application.RunLoop (bool,System.Windows.Forms.ApplicationContext) <0x00d0f>
  at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext) <0x00057>
  at System.Windows.Forms.Application.Run (System.Windows.Forms.Form) <0x00037>
  at PKHeX.Program.Main () <0x0003b>
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) <0x000ba>

Native stacktrace:

	mono() [0x4acddf]
	mono() [0x500dce]
	mono() [0x428a43]
	/usr/lib/libpthread.so.0(+0x10f00) [0x7f4fd1c75f00]
	/usr/lib/libc.so.6(strlen+0x26) [0x7f4fd172bd76]
	/usr/lib/libX11.so.6(_XimLocalUtf8LookupString+0xeb) [0x7f4fcdbb4b1b]
	[0x41e33975]

Debug info from gdb:

[New LWP 32725]
[New LWP 32726]
[New LWP 32734]
[New LWP 32735]
[New LWP 32736]
warning: File "/usr/bin/mono-sgen-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/bin/mono-sgen-gdb.py
line to your configuration file "/home/user/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/user/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007f4fd1c75b5b in waitpid () from /usr/lib/libpthread.so.0
  Id   Target Id         Frame 
* 1    Thread 0x7f4fd2782780 (LWP 32724) "mono" 0x00007f4fd1c75b5b in waitpid () from /usr/lib/libpthread.so.0
  2    Thread 0x7f4fd0fff700 (LWP 32725) "mono" 0x00007f4fd1c720af in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  3    Thread 0x7f4fce597700 (LWP 32726) "Finalizer" 0x00007f4fd1c74497 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  4    Thread 0x7f4fbf973700 (LWP 32734) "mono" 0x00007f4fd1c72458 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  5    Thread 0x7f4fbeede700 (LWP 32735) "Threadpool work" 0x00007f4fd1c72458 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  6    Thread 0x7f4fbecdd700 (LWP 32736) "Threadpool work" 0x00007f4fd1c72458 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0

Thread 6 (Thread 0x7f4fbecdd700 (LWP 32736)):
#0  0x00007f4fd1c72458 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000059d13a in ?? ()
#2  0x0000000000597dd1 in ?? ()
#3  0x0000000000648a6a in ?? ()
#4  0x00007f4fd1c6c484 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f4fd17956dd in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7f4fbeede700 (LWP 32735)):
#0  0x00007f4fd1c72458 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000059d13a in ?? ()
#2  0x0000000000597dd1 in ?? ()
#3  0x0000000000648a6a in ?? ()
#4  0x00007f4fd1c6c484 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f4fd17956dd in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7f4fbf973700 (LWP 32734)):
#0  0x00007f4fd1c72458 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000064759d in ?? ()
#2  0x000000000059c1b1 in ?? ()
#3  0x0000000000597dd1 in ?? ()
#4  0x0000000000648a6a in ?? ()
#5  0x00007f4fd1c6c484 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f4fd17956dd in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7f4fce597700 (LWP 32726)):
#0  0x00007f4fd1c74497 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007f4fd1c74544 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x00000000005b7d57 in ?? ()
#3  0x0000000000597dd1 in ?? ()
#4  0x0000000000648a6a in ?? ()
#5  0x00007f4fd1c6c484 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f4fd17956dd in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7f4fd0fff700 (LWP 32725)):
#0  0x00007f4fd1c720af in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x0000000000617283 in ?? ()
#2  0x00007f4fd1c6c484 in start_thread () from /usr/lib/libpthread.so.0
#3  0x00007f4fd17956dd in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f4fd2782780 (LWP 32724)):
#0  0x00007f4fd1c75b5b in waitpid () from /usr/lib/libpthread.so.0
#1  0x00000000004aceb6 in ?? ()
#2  0x0000000000500dce in ?? ()
#3  0x0000000000428a43 in ?? ()
#4  <signal handler called>
#5  0x00007f4fd172bd76 in strlen () from /usr/lib/libc.so.6
#6  0x00007f4fcdbb4b1b in _XimLocalUtf8LookupString () from /usr/lib/libX11.so.6
#7  0x0000000041e33975 in ?? ()
#8  0x0000000000000000 in ?? ()

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

[1]    32724 abort (core dumped)  mono ~/programs/PKHeX.exe

```

**Comment by kwsch** [comment]
@Zekario , lets [try this](https://dl.dropboxusercontent.com/u/12206225/pporg/PKHeX/PKHeX%20(fix2_07-30-16).zip) again :)

**Comment by Zekario** [comment]
@kwsch It seems to work in WINE now, but I thought I would let you know the super/windows key bug still seems to affect when it runs with Mono. Thanks!

**Comment by kwsch** [comment]
Looks like the Wine exception is related to X11Keyboard; probably related to a Wine issue instead of the program.

PKHeX's main window is FixedSingle, meaning it can't be resized (or maximized). Looks like your tiling WM is ignoring/overriding that property. Nothing I can really do about it :(

**Comment by Zekario** [comment]
Ah, I see. Thank you for making it compatible!

**Comment by Airblader** [comment]
> Looks like your tiling WM is ignoring/overriding that property. Nothing I can really do about it :(

A window manager has full authority to size the window any way it likes. Any application *has* to expect and deal with that according to the ICCCM.
