### ISSUE TITLE
PKHeX Error viewing Simipour

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#1515]
```
Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PKHeX.Core.PKM.GetStats(PersonalInfo p)
   at PKHeX.WinForms.Controls.PKMEditor.UpdateStats() in D:\Nyron\Dropbox\PKHeX\PKHeX.WinForms\Controls\PKM Editor\PKMEditor.cs:line 481
   at PKHeX.WinForms.Controls.PKMEditor.UpdateForm(Object sender, EventArgs e) in D:\Nyron\Dropbox\PKHeX\PKHeX.WinForms\Controls\PKM Editor\PKMEditor.cs:line 1094
   at PKHeX.WinForms.Controls.PKMEditor.UpdateSpecies(Object sender, EventArgs e) in D:\Nyron\Dropbox\PKHeX\PKHeX.WinForms\Controls\PKM Editor\PKMEditor.cs:line 1244
   at System.Windows.Forms.ListControl.OnSelectedValueChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedValueChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at System.Windows.Forms.ListControl.set_SelectedValue(Object value)
   at PKHeX.WinForms.Controls.PKMEditor.LoadSpeciesLevelEXP(PKM pk) in D:\Nyron\Dropbox\PKHeX\PKHeX.WinForms\Controls\PKM Editor\LoadSave.cs:line 26
   at PKHeX.WinForms.Controls.PKMEditor.LoadMisc1(PKM pk) in D:\Nyron\Dropbox\PKHeX\PKHeX.WinForms\Controls\PKM Editor\LoadSave.cs:line 230
   at PKHeX.WinForms.Controls.PKMEditor.PopulateFieldsPK5() in D:\Nyron\Dropbox\PKHeX\PKHeX.WinForms\Controls\PKM Editor\EditPK5.cs:line 12
   at PKHeX.WinForms.Controls.PKMEditor.PopulateFields(PKM pk, Boolean focus) in D:\Nyron\Dropbox\PKHeX\PKHeX.WinForms\Controls\PKM Editor\PKMEditor.cs:line 200
   at PKHeX.WinForms.Controls.ContextMenuSAV.ClickView(Object sender, EventArgs e) in D:\Nyron\Dropbox\PKHeX\PKHeX.WinForms\Controls\SAV Editor\ContextMenuSAV.cs:line 36
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\Nyron\Dropbox\PKHeX\PKHeX.WinForms\bin\Release\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\Nyron\Dropbox\PKHeX\PKHeX.WinForms\bin\Release\PKHeX.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```

[516 - Simipour - E4D508102040.zip](https://github.com/kwsch/PKHeX/files/1364148/516.-.Simipour.-.E4D508102040.zip)

**Comment by kwsch** [comment]
nature is hacked, nature ID 0x20 (32) is beyond 0x19 (25)
