### ISSUE TITLE
[Error] Could not auto-load savefile on build 4074 or 4079

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1585]
Upon launch PKHeX gives the following error:
"An error occurred while attempting to auto-load your safefile."
Thank you for taking the time to read this and for all your work with PKHeX.
```
Exception Details:
System.IO.IOException: The file or directory is corrupted and unreadable.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at PKHeX.WinForms.PathUtilWindows.DetectSaveFile(String& path, String[] extra)
   at PKHeX.WinForms.Main.DetectSaveFile(String& path)
   at PKHeX.WinForms.Main.FormLoadInitialFiles(String[] args)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.4079, Culture=neutral, PublicKeyToken=null
C:\Users\gD\Desktop\PKHeX\4079\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

--------------------
User Message:
An error occurred while attempting to auto-load your save file.
```

**Comment by kwsch** [comment]
>System.IO.IOException: The file or directory is corrupted and unreadable.

gee, wonder why. bad files on the sd card?

**Comment by greenDarkness** [comment]
PKHeX was able to read the save when I dragged it directly into the program. So I guess that leaves the directory.

**Comment by greenDarkness** [comment]
I did an error-check scan with Windows and it said that my drive didn't have any problems.
I also checked all the folders inside the JKSM folder; which is was I used to dump the save.

EDIT: Removed my SD card, re-inserted it, and launched PKHeX. The error didn't happen this time.
Dunno what the problem was. Sorry to take up any of your time. Thanks for the help!
