### ISSUE TITLE
I keep getting unhanded extension error when I go to export my file

### ISSUE THREAD

**Issue by ceruleanfitness** [kwsch/PKHeX#162]
this is the message I keep getting. If someone can help I would greatly appreciate it I have not been able to pokegen for months and can't seem to fix this. I am doing this on my MAC BOOK PRO and have been doing it for over a year perfectly fine until the past 3 months it stopped working
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'F:\saveDataBackup\main' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at PKHeX.Main.clickExportSAV(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PKHeX
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/winebottler/PKHeX.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by evandixon** [comment]
Try saving it elsewhere; it could be that you don't have write permissions to that directory.

**Comment by ceruleanfitness** [comment]
I'm not quite sure what that means. From what I know it needs to be saved in the savedata folder where its called (main) if I try saving to my desktop or anywhere else it does not work so I have no idea whats wrong

**Comment by kwsch** [comment]
Try saving it to your desktop instead of to your SD card.
Double check that the SD card's [Write Protect Tab is in the Upwards position](http://i.fixya.net/uploads/images/bea21a9.jpg).

Double check that the executable isn't blocked by antivirus / operating system protections before extracting from the ZIP file.

[See associated forum post for more information](https://projectpokemon.org/forums/showthread.php?47063-PKHeX-error).

**Comment by ceruleanfitness** [comment]
done all those things its all ok and the file has to be saved in that specific location because when I turn the game on thats where it has to load the file from on my Nintendo 3DS. Do you or anyone know how to fix that unhanded extension error and how to enable just-in-time (JIT) debugging?

**Comment by kwsch** [comment]
Again, save it to your computer then use your computer to the copy it to the specific location.

**Comment by kwsch** [comment]
https://projectpokemon.org/forums/showthread.php?47063-PKHeX-error

**Comment by ceruleanfitness** [comment]
I did that, it did not work

**Comment by ceruleanfitness** [comment]
the side of my SD card was not locked and when I saved the main file to another location on my computer and tried to drag it into my save folder for the game so it will upload on my 3DS it shows a circle with a line through it (the censor sign) and prevents me from placing it
![error](https://cloud.githubusercontent.com/assets/20824954/17456601/6965ed68-5bab-11e6-9d15-5af78d3b32b3.JPG)

**Comment by ceruleanfitness** [comment]
could it be because they updated the files? I have the latest PKhex but I think I have the older version of oothax (I use the ocarina of time method to get to home-brew)
