### ISSUE TITLE
Import set from clipboard

### ISSUE THREAD

**Issue by ShadowsGod97** [kwsch/PKHeX#1726]
Tried to import a set from Showdown and got an error
![1514151446071987264536](https://user-images.githubusercontent.com/30508666/34329290-63404188-e8c0-11e7-9ff2-7efbb2e05dea.jpg)

**Comment by Ntonio36** [comment]
Could you post the showdown set you were trying to import?

**Comment by ShadowsGod97** [comment]
Doesn't matter it won't let me import

**Comment by kwsch** [comment]
Can't resolve without either the details or the set text that was attempted to be imported.

**Comment by ShadowsGod97** [comment]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PKHeX.WinForms.Main.ClickShowdownImportPKM(Object sender, EventArgs e) in C:\Users\COMPAQ\Desktop\241217\PKHeX-master\PKHeX-master\PKHeX.WinForms\MainWindow\Main.cs:line 412
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by kwsch** [comment]
Main.cs line 412 has nothing; I assume this is a modified version of the PKHeX codebase thus not related to this repository.
