### ISSUE TITLE
HGSS Pichu dex data

### ISSUE THREAD

**Issue by SpiredMoth** [kwsch/PKHeX#1828]
Whenever I try to view Pichu's dex data from an unmodified HGSS file I get this error
```
Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PKHeX.WinForms.SAV_Pokedex4.<>c__DisplayClass14_0.<GetEntry>b__1(Int32 v, Int32 i)
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PKHeX.WinForms.SAV_Pokedex4.GetEntry()
   at PKHeX.WinForms.SAV_Pokedex4.ChangeLBSpecies(Object sender, EventArgs e)
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Brandon\Programs\Pokemon\PKHeX (180128)\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Brandon\Programs\Pokemon\PKHeX (180128)\PKHeX.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```

If I use one of the dex modify options first (Seen all, Captured all, Complete Dex), everything seems to work as normal.
If I export and load the save after that, the game doesn't recognize Spiky-eared has having been seen despite PKHeX reporting otherwise.

This happens with multiple unmodified files that and result in the following
```
Source    Value   Game shows
file 1    0xD8    male, Spiky-eared, female
file 2    0xF8    male, Spiky-eared
PKHeX     0xF4    male, female
```

**Comment by kwsch** [comment]
Not able to replicate on latest commit with any of my save files...

Please upload a save file that can replicate the crash.

**Comment by SpiredMoth** [comment]
This is the "file 1" one I mentioned. I've had it since release day so I'm certain it comes from a legit cart


[hgss-pichu.zip](https://github.com/kwsch/PKHeX/files/1713866/hgss-pichu.zip)

**Comment by kwsch** [comment]
`D8 = 11011000 = ~, 01, 10, 00`
`F8 = 11111000 = ~, ~, 10, 00`
`F4 = 11110100 = ~, ~, 01, 00`

Where,
00 = male
01 = female
10 = spiky

looks like it's just an edge case...
