### ISSUE TITLE
Showdown Import in Previous Generations Throws Exception

### ISSUE THREAD

**Issue by DaWoblefet** [kwsch/PKHeX#1929]
When attempting to import a Showdown set into Pokemon Emerald, X, ORAS, or White 2, I received the exception listed below. Trying to import into Pokemon SoulSilver, PKHeX did not throw an exception, and instead just straight up crashed and had to be force-quit. I tried other sets besides this Aron, and they threw the same exception.

Aron (F) @ Shell Bell  
Ability: Sturdy  
Level: 1  
EVs: 116 Atk / 36 Spe  
Jolly Nature  
- Endeavor  
- Stealth Rock  
- Iron Head  
- Protect

Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.Core.CommonEdits.ApplySetDetails(PKM pk, ShowdownSet Set)
   at PKHeX.WinForms.Controls.PKMEditor.LoadShowdownSetDefault(ShowdownSet Set)
   at PKHeX.WinForms.Main.ClickShowdownImportPKM(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\dawob\Documents\PKHeX (4-17-18)\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\dawob\Documents\PKHeX (4-17-18)\PKHeX.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by sora10pls** [comment]
Are you using the latest commit? Unable to replicate this.
![image](https://user-images.githubusercontent.com/17801814/39676382-eab1231e-5137-11e8-82f8-b3946956998d.png)

**Comment by kwsch** [comment]
@sora10pls probably due to updating the PID
