### ISSUE TITLE
not available pokemon suggestmove

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2030]
![image](https://user-images.githubusercontent.com/39662364/41816231-299114ae-77b2-11e8-9ec4-81b2b7205f60.png)

![image](https://user-images.githubusercontent.com/39662364/41816247-77b9971e-77b2-11e8-87a1-02106db3777f.png)

[151 ★ - ミュウ - 8F87.zip](https://github.com/kwsch/PKHeX/files/2130482/151.-.-.8F87.zip)

```
Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.Core.LegalityAnalysis.GetSuggestedMoves(Boolean tm, Boolean tutor, Boolean reminder)
   at PKHeX.Core.CommonEdits.GetMoveSet(PKM pkm, Boolean random, LegalityAnalysis la)
   at PKHeX.WinForms.Controls.PKMEditor.SetSuggestedMoves(Boolean random, Boolean silent)
   at PKHeX.WinForms.Controls.PKMEditor.ClickMoves(Object sender, EventArgs e)
```

**Comment by iiippppk** [comment]
close
