### ISSUE TITLE
Batch editor unhandled exception

### ISSUE THREAD

**Issue by frostheart32** [kwsch/PKHeX#2032]
In the newest release, I keep getting the following unhandled exception when using the batch editor.

```
Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PKHeX.Core.BatchEditing.GetPropertyType(String propertyName, Int32 typeIndex)
   at PKHeX.WinForms.BatchEditor.CB_Property_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at PKHeX.WinForms.BatchEditor.CB_Format_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
```

When I use the batch editor after continuing past this error message, the values it edits are either wrong or produce illegal pokemon.

I've downloaded a fresh copy of pkhex and replaced the existing files a couple of times.

I've downloaded the newest version of net framework for windows and restarted it.

I've cleared the user appdata folder each time I download a new copy of pkhex to ensure that isn't causing the issue.

Any help in solving this problem would be appreciated.

Thanks,
Frosty

**Comment by kwsch** [comment]
Works fine on the latest commit, was fixed since the last release.
https://github.com/kwsch/PKHeX/commit/dcfeff7bf3c1d9cf9a253396a138ae95461fac43#diff-30e33111e912fe5de5b9ffa0cf33909eR90
