### ISSUE TITLE
Get this error upon clicking open. 

### ISSUE THREAD

**Issue by makiharukawa** [kwsch/PKHeX#2295]
I was told to update a while ago, which i did, and it worked fine till now. Now i get this error. It occurs when I do not have my sd card in my computer.

Exception Details:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.WinForms.Main.MainMenuOpen(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```

**Comment by kwsch** [comment]
Please try running the program with the attached debug build. Hopefully it gives a better error message, since MainMenuOpen doesn't have any object-oriented logic to throw an exception with.
[PKHeX 190504.zip](https://github.com/kwsch/PKHeX/files/3145116/PKHeX.190504.zip)

**Comment by makiharukawa** [comment]
Debug build doesnt give an error and properly opens the file explorer!
