### ISSUE TITLE
error report | gen 2 cartridge save file

### ISSUE THREAD

**Issue by TsubasaLi** [kwsch/PKHeX#2366]
```
Exception Details:
System.ArgumentOutOfRangeException: InvalidArgument=Value of '211' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at PKHeX.WinForms.SAV_SimpleTrainer..ctor(SaveFile sav)
   at PKHeX.WinForms.Controls.SAVEditor.B_OpenTrainerInfo_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=19.7.5.0, Culture=neutral, PublicKeyToken=null
[snip]

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```

This error only occurs when I press the "Trainer Info" button in pkhex. As stated in the title, it's not a VC save file but a genuine cartridge save file. In my case, it's the Japanese version of crystal. I dumped the save file with the GB-01 Cartridge Reader which has worked totally fine on my PC but on my laptop it doesn't seem to want to "work" (everything but accessing Trainer Info works properly.

**Comment by kwsch** [comment]
Can't replicate, please send the savefile (forums/discord).
Here's what it normally looks like:
![image](https://user-images.githubusercontent.com/6393368/61987502-f9761c80-afcb-11e9-8717-abf91c4de11e.png)

**Comment by kwsch** [comment]
Closed due to inactivity.
