### ISSUE TITLE
Error Opening Pokemon Diamond

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2376]
```
Exception Details:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: box
   at PKHeX.Core.BoxEdit.LoadBox(Int32 box)
   at PKHeX.WinForms.Controls.BoxEditor.InitializeFromSAV(SaveFile sav) in ~PKHeX\PKHeX.WinForms\Controls\SAV Editor\BoxEditor.cs:line 259
   at PKHeX.WinForms.Controls.SAVEditor.ToggleViewReset() in ~PKHeX\PKHeX.WinForms\Controls\SAV Editor\SAVEditor.cs:line 923
   at PKHeX.WinForms.Controls.SAVEditor.ToggleInterface() in ~PKHeX\PKHeX.WinForms\Controls\SAV Editor\SAVEditor.cs:line 897
   at PKHeX.WinForms.Main.ResetSAVPKMEditors(SaveFile sav) in ~PKHeX\PKHeX.WinForms\MainWindow\Main.cs:line 779
   at PKHeX.WinForms.Main.OpenSAV(SaveFile sav, String path) in ~PKHeX\PKHeX.WinForms\MainWindow\Main.cs:line 738
   at PKHeX.WinForms.Main.LoadFile(Object input, String path) in ~PKHeX\PKHeX.WinForms\MainWindow\Main.cs:line 602
   at PKHeX.WinForms.Main.OpenFile(Byte[] input, String path, String ext) in ~PKHeX\PKHeX.WinForms\MainWindow\Main.cs:line 584
   at PKHeX.WinForms.Main.OpenFromPath(String path) in ~PKHeX\PKHeX.WinForms\MainWindow\Main.cs:line 576

--------------------
User Message:
Unable to load file.
Path: ~Emulators\DeSmuME\Battery\Pokemon Diamond Version.dsv
```

**Comment by kwsch** [comment]
Exception is being thrown here:
https://github.com/kwsch/PKHeX/blob/bf6c25eca72787a2a08bfbf65cafd89fe7bedc92/PKHeX.Core/Editing/Saves/Slots/BoxEdit.cs#L19-L26

Looks like CurrentBox is either negative or above the acceptable range...

**Comment by Ninjistix** [comment]
I only collected the starter Pokemon.

**Comment by Ninjistix** [comment]
[Pokemon Diamond Version.zip](https://github.com/kwsch/PKHeX/files/3532720/Pokemon.Diamond.Version.zip)
here's the sav file forgot to attach it earlier

**Comment by Ninjistix** [comment]
regarding f0df115ccd2d08e52144960a88b0abaebbd31a6a 

I'm having this issue with the box in Diamond (in red) vs pearl (in green)
![image](https://user-images.githubusercontent.com/12572974/63633449-b6cd5180-c616-11e9-8e81-11cc7d39c89a.png)

**Comment by Ninjistix** [comment]
to fix this issue, I had to catch a Pokemon in Diamond then deposit it into the box via in game PC, then save game and reload save with PKHEX to gain access to the box.
