### ISSUE TITLE
An unhandled exception has occurred:

### ISSUE THREAD

**Issue by BetaLeaf** [kwsch/PKHeX#2485]
**Describe the bug**
Trying to suggest a Met Location on Sword & Shield Sirfetch'd causes unhandled exception.

**To Reproduce**
1. Import this PKM: [865 - Sirfetch'd - 1CAA8ABE6C1B.pk8](https://github.com/kwsch/PKHeX/files/3873602/865.-.Sirfetch.d.-.1CAA8ABE6C1B.zip)
2. Go to `Met` tab and ctrl+click `Met Location` label text.
3. An unhandled exception has occurred.

**Expected behavior**
A met location should be suggested.

**Additional context**
Seems to work fine if As Egg is checked. 

Let me know if there's anything else I can do to help.

Log:
```
Exception Details:
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at PKHeX.Core.EditPKMUtil.GetSuggestionMessage(PKM pkm, Int32 level, Int32 location, Int32 minlvl)
   at PKHeX.WinForms.Controls.PKMEditor.SetSuggestedMetLocation(Boolean silent)
   at PKHeX.WinForms.Controls.PKMEditor.ClickMetLocation(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=19.11.15.0, Culture=neutral, PublicKeyToken=null
D:\Nextcloud\PKHeX\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null


System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null


Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```

**Comment by Bappsack** [comment]
working fine on latest commit.

**Comment by BetaLeaf** [comment]
Ok I will update the latest version. I just checked and I was running 19/11/15 - New Update

**Comment by BetaLeaf** [comment]
Ok I bothered to build to build from source and can confirm this is not an issue and has already been fixed. Sorry for the false report.
