### ISSUE TITLE
Unhandled exception when copy legality report to clipboard

### ISSUE THREAD

**Issue by BetaLeaf** [kwsch/PKHeX#2486]
**Describe the bug**
Unhandled exception when copy legality report to clipboard

**To Reproduce**
1. Import this PKM: [888 - Zacian - A6E9A9C54569.pk8](https://github.com/kwsch/PKHeX/files/3873997/888.-.Zacian.-.A6E9A9C54569.zip)
2. Ctrl+click legal check
3. Select `Yes` when asked to copy report to clipboard.

**Expected behavior**
No unhandled exception

**Additional context**
On commit 422b11bb4217daf825d4a5bb9a5223405819f14c

Log:
```
Exception Details:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=19.11.15.0, Culture=neutral, PublicKeyToken=null
D:\Nextcloud\PKHeX\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null


System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null


--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```

**Comment by Bappsack** [comment]
also works fine on latest commit.

**Comment by BetaLeaf** [comment]
I am on the latest commit. Doesn't work for me

**Comment by ReignOfComputer** [comment]
Exception suggests that your OS Clipboard is currently locked by another application. I can't reproduce this issue, we could wrap the clipboard function in a try-catch but I think the problem in this case doesn't lie with PKHeX.

**Comment by BetaLeaf** [comment]
I use the Windows 10 Clipboard Manager included with newer versions of
window. Maybe that's it?

**Comment by ReignOfComputer** [comment]
I just tested against that, works for me.

**Comment by BetaLeaf** [comment]
Any idea how I can figure out what is locking the Clipboard? I don't even
have anti virus enabled.
