### ISSUE TITLE
Unhandled exception when changing default blank save game

### ISSUE THREAD

**Issue by Gliscor** [kwsch/PKHeX#2514]
**Describe the bug**
Unhandled exception when changing default blank save game.

**To Reproduce**
1. Go to 'options'
2. Click on 'settings'
3. Choose any game from the drop-down menu
4. click on the "x" to close
5. See error

**Expected behavior**
no error.

**Screenshots**

**Additional context**
Exception details:

Exception Details:
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at PKHeX.Core.ArrayUtil.Slice(Byte[] src, Int32 offset, Int32 length)
   at PKHeX.Core.SaveFile.GetStoredSlot(Byte[] data, Int32 offset)
   at PKHeX.WinForms.Controls.SAVEditor.UpdateSlot(Int32 relIndex)
   at PKHeX.WinForms.Controls.SAVEditor.ResetDaycare()
   at PKHeX.WinForms.Controls.SAVEditor.ResetNonBoxSlots()
   at PKHeX.WinForms.Controls.SAVEditor.ToggleInterface()
   at PKHeX.WinForms.Main.ResetSAVPKMEditors(SaveFile sav)
   at PKHeX.WinForms.Main.OpenSAV(SaveFile sav, String path)
   at PKHeX.WinForms.Main.LoadBlankSaveFile(GameVersion ver)
   at PKHeX.WinForms.Main.MainMenuSettings(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=19.11.15.0, Culture=neutral, PublicKeyToken=null
C:\Users\Queso\Desktop\PKHeX\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/issues/2481
