### ISSUE TITLE
Unhandled exception has occurred (Sorry if this isn't a technical bug or not)

### ISSUE THREAD

**Issue by TheGho7t** [kwsch/PKHeX#2944]
I just finished Pokemon Emerald on my 3ds Virtual Console and it unfortunately said that it deleted my save data. I assume it's because it's on VC that it doesn't actually delete it, but nonetheless, I tried to see if I could recover it in any form. My Pokemon still randomly show up, with all of their stats being correct, no issues there. I believe I can move them to another save, if necessary, which is good.

I didn't want to go through 20+ hours of running the gyms again, which is why I'm here now. The checksums say they are valid and I get no popup unless I hit "Event Flags", "Misc Edits" or "Mail Box".

Each error is different, so I will place them in order here.

1. Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PKHeX.Core.FlagUtil.GetFlag(Byte[] arr, Int32 offset, Int32 bitIndex)
   at PKHeX.Core.SAV3.GetEventFlag(Int32 flagNumber)
   at PKHeX.Core.SaveFile.get_EventFlags()
   at PKHeX.WinForms.SAV_EventFlags..ctor(SaveFile sav)
   at PKHeX.WinForms.Controls.SAVEditor.B_OpenEventFlags_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

2. Exception Details:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToUInt32(Byte[] value, Int32 startIndex)
   at PKHeX.Core.Record3.GetRecord(Int32 record)
   at PKHeX.WinForms.SAV_Misc3.<>c__DisplayClass39_0.<LoadRecords>g__LoadRecordID|6(Int32 index)
   at PKHeX.WinForms.SAV_Misc3.LoadRecords()
   at PKHeX.WinForms.SAV_Misc3..ctor(SaveFile sav)
   at PKHeX.WinForms.Controls.SAVEditor.B_OpenMiscEditor_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

3. Exception Details:
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: srcOffset
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at PKHeX.WinForms.SAV_MailBox..ctor(SaveFile sav)
   at PKHeX.WinForms.Controls.SAVEditor.B_MailBox_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I wasn't sure if there was any helping on this, just thought I'd ask here though in case. Thank you for your time and thank you very much for making a very user friendly and enjoyable program. (I love messing around with it and this is the first time it has ever messed up)

**Comment by kwsch** [comment]
3DS VC save files are not official save file types; if your savedata isn't in the format that the program expects (eg a block of data is missing), you end up with improper saves that can't be handled.

Works fine for regular (valid) saves.

**Comment by TheGho7t** [comment]
Well that's interesting, considering I've transferred saved files over before and had no issues whatsoever with editing anything. I had no idea it was different. It looked like the exact same to me.

Thanks for the response and keep up the good work.

**Comment by Ammako** [comment]
You have to set the save file type to 128 KB flash when building the CIA. New Super Ultimate Injector should do this automatically (and if it doesn't, you can change the save file type at the bottom.) Don't use Ultimate GBA VC injector, it doesn't do 128 KB flash.
