### ISSUE TITLE
[Ryujinx] pulling up the map crashes the games.

### ISSUE THREAD

**Issue by yoshifanx** [kwsch/PKHeX#3681]
**Describe the bug**

**To Reproduce**
1. Open the game in Ryujinx with a randomizer mod applied
2. Press Y to open the map (assuming you have unlocked it)
3. Game freezes and then crashes with the below error in the ryujinx console
`00:01:27.553 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:01:27.608 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 275
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 130
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
`

**Expected behavior**
The map should pull up showing all pokemon in the surrounding area.

**Screenshots**
![image](https://user-images.githubusercontent.com/69432779/206745796-c4893bd3-ca73-44e7-88ec-e2644438bae2.png)

**Additional context**
- Running Latest Ryujinx (1.1.454)
- Running system version 14.1.2
- Tested without randomization applied (in case it was ryujinx related bug). Map opens fine.

**Comment by sora10pls** [comment]
This has nothing to do with PKHeX.
