### ISSUE TITLE
Crash on LocalizeUtil.InitializeStrings()

### ISSUE THREAD

**Issue by codemonkey85** [kwsch/PKHeX#3893]
**Describe the bug**
When I try to initialize strings, the app crashes with an exception.

**To Reproduce**
1. Try this code: `LocalizeUtil.InitializeStrings(CurrentLanguage, SaveFile);` (where `CurrentLanguage = GameLanguage.DefaultLanguage` and `SaveFile == null`).
2. The app crashes.
NOTE: This code worked in 23.4.6, and it's broken in 23.5.11. I made no other changes.

**Expected behavior**
I expect the strings to be initialized and the app to continue operating.

**Screenshots**
<img width="745" alt="image" src="https://github.com/kwsch/PKHeX/assets/1414036/2348d492-04f9-40df-9353-0f774a9f3d2e">

**Additional context**
This is in the context of a Blazor WebAssembly app targeting .NET 7.0.5, SDK 7.0.203. The repo is here: https://github.com/codemonkey85/PKMDS-Blazor/, the specific line is here: https://github.com/codemonkey85/PKMDS-Blazor/blob/b2a98355c83a5af4ccc0de0c1b689efd1bbca83f/Pkmds.Rcl/AppState.cs#L7

<details>
  <summary>Full stacktrace:</summary>

```
System.AggregateException: AggregateException_ctor_DefaultMessage (TypeInitialization_Type, PKHeX.Core.GameInfo)
 ---> System.TypeInitializationException: TypeInitialization_Type, PKHeX.Core.GameInfo
 ---> System.TypeInitializationException: TypeInitialization_Type, PKHeX.Core.Legal
 ---> System.ArgumentException: Cannot initialize array of non-primitive type Arg_ParamName_Name, array
   at System.Runtime.CompilerServices.RuntimeHelpers.GetSpanDataFrom(RuntimeFieldHandle , RuntimeTypeHandle , Int32& )
   at System.Runtime.CompilerServices.RuntimeHelpers.CreateSpan[InventoryType](RuntimeFieldHandle )
   at PKHeX.Core.ItemStorage9SV.get_ValidHeldTypes()
   at PKHeX.Core.ItemStorage9SV.GetAllHeld()
   at PKHeX.Core.Legal..cctor()
   Exception_EndOfInnerExceptionStack
   at PKHeX.Core.FakeSaveFile.get_HeldItems()
   at PKHeX.Core.FilteredGameDataSource..ctor(SaveFile sav, GameDataSource source, Boolean HaX)
   at PKHeX.Core.GameInfo..cctor()
   Exception_EndOfInnerExceptionStack
   at PKHeX.Core.GameInfo.GetStrings(String lang)
   at PKHeX.Core.LocalizeUtil.InitializeStrings(String lang, SaveFile sav, Boolean hax)
   at Pkmds.Rcl.AppState..ctor()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite , RuntimeResolverContext , ServiceProviderEngineScope , RuntimeResolverLock )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type )
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider , IComponent )
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider , IComponent )
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider , Type )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type )
   at Microsoft.AspNetCore.Components.RenderTree.WebRenderer.AddRootComponent(Type , String )
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.AddComponentAsync(Type , ParameterView , String )
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.<>c.<<RunAsyncCore>b__15_1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsyncCore(CancellationToken , WebAssemblyCultureProvider )
   at Program.<Main>$(String[] args)
   Exception_EndOfInnerExceptionStack
```

</details>

**Comment by codemonkey85** [comment]
Forgot to mention, this code worked in 23.4.6, and it's broken in 23.5.11. I made no other changes.

**Comment by codemonkey85** [comment]
FYI, I'm getting a very similar issue with GameInfo.FilteredSources:

<details>
  <summary>Full stacktrace:</summary>

```
System.AggregateException: AggregateException_ctor_DefaultMessage (TypeInitialization_Type, PKHeX.Core.GameInfo)
 ---> System.TypeInitializationException: TypeInitialization_Type, PKHeX.Core.GameInfo
 ---> System.TypeInitializationException: TypeInitialization_Type, PKHeX.Core.Legal
 ---> System.ArgumentException: Cannot initialize array of non-primitive type Arg_ParamName_Name, array
   at System.Runtime.CompilerServices.RuntimeHelpers.GetSpanDataFrom(RuntimeFieldHandle , RuntimeTypeHandle , Int32& )
   at System.Runtime.CompilerServices.RuntimeHelpers.CreateSpan[InventoryType](RuntimeFieldHandle )
   at PKHeX.Core.ItemStorage9SV.get_ValidHeldTypes()
   at PKHeX.Core.ItemStorage9SV.GetAllHeld()
   at PKHeX.Core.Legal..cctor()
   Exception_EndOfInnerExceptionStack
   at PKHeX.Core.FakeSaveFile.get_HeldItems()
   at PKHeX.Core.FilteredGameDataSource..ctor(SaveFile sav, GameDataSource source, Boolean HaX)
   at PKHeX.Core.GameInfo..cctor()
   Exception_EndOfInnerExceptionStack
   at PKHeX.Core.GameInfo.GetStrings(String lang)
   at PKHeX.Core.LocalizeUtil.InitializeStrings(String lang, SaveFile sav, Boolean hax)
   at Pkmds.Rcl.AppState..ctor()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite , RuntimeResolverContext , ServiceProviderEngineScope , RuntimeResolverLock )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type )
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider , IComponent )
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider , IComponent )
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider , Type )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type )
   at Microsoft.AspNetCore.Components.RenderTree.WebRenderer.AddRootComponent(Type , String )
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.AddComponentAsync(Type , ParameterView , String )
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.<>c.<<RunAsyncCore>b__15_1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsyncCore(CancellationToken , WebAssemblyCultureProvider )
   at Program.<Main>$(String[] args)
   Exception_EndOfInnerExceptionStack
```

</details>

**Comment by codemonkey85** [comment]
Looks like this is an issue with the way Blazor WASM / Mono handles initializing arrays of "non-primitive types" (https://github.com/dotnet/roslyn/pull/61414). I'm gonna take it to MS and hope they can deal with it. Thank you!

**Comment by codemonkey85** [comment]
One last comment - here is the issue I created to track this fix, in case anyone using Blazor (or .NET MAUI?) needs this fixed as well: https://github.com/dotnet/aspnetcore/issues/48500

**Comment by codemonkey85** [comment]
In case anyone stumbles on this looking for a solution - it looks like this issue has been resolved both in .NET 8 and .NET 7 SDK 7.0.9 / 7.0.306.
