### ISSUE TITLE
Error upon loading Gen 1 saves

### ISSUE THREAD

**Issue by gnmmarechal** [kwsch/PKHeX#411]
```
Exception Details:
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at PKHeX.GameInfo.setItemDataSource(Boolean HaX, Int32 MaxItemID, IEnumerable`1 allowed, Int32 generation, GameVersion game, GameStrings s) in C:\Users\gnmso\Source\Repos\PKHeX\PKHeX\Game\GameInfo.cs:line 341
   at PKHeX.Main.populateFilteredDataSources() in C:\Users\gnmso\Source\Repos\PKHeX\PKHeX\MainWindow\Main.cs:line 1348
   at PKHeX.Main.openSAV(SaveFile sav, String path) in C:\Users\gnmso\Source\Repos\PKHeX\PKHeX\MainWindow\Main.cs:line 1158
   at PKHeX.Main.openFile(Byte[] input, String path, String ext) in C:\Users\gnmso\Source\Repos\PKHeX\PKHeX\MainWindow\Main.cs:line 673
   at PKHeX.Main.openQuick(String path, Boolean force) in C:\Users\gnmso\Source\Repos\PKHeX\PKHeX\MainWindow\Main.cs:line 636

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\gnmso\Source\Repos\PKHeX\PKHeX\bin\Debug\PKHeX.exe

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

--------------------
User Message:
Unable to load file.
Path: C:\Users\gnmso\Downloads\Pokemon Red.sav

```

The editor seems to work after I press Continue. The latest stable doesn't have any issue with the same save, but the latest commit does this.

**Comment by kwsch** [comment]
Duplicate with #339
