### ISSUE TITLE
Pkhex errors out in Winlator

### ISSUE THREAD

**Issue by Wolf-lbh** [kwsch/PKHeX#4317]
**How I got to this point**
Long story short I''m going on trip to a place without internet for a month and packing a laptop is not advised so I'm limited to just having my phone to keep me occupied for a month's worth of free time. I have some ebooks, music, and movies on my phone but I really wanted to enjoy emulating a bunch of games. The issue being I wanted to play Pokemon games and that would lock me out of the cool trade evolutions as well as event Pokemon. No problem I thought I'll just use Pkhex, except it turns out there was no android version. So I tried putting PKSM on lime3ds only to find out it only runs on real jailbroken 3ds consoles and not emulators for some reason. At this point I went for the nuclear option and decided to emulate all of Windows on my phone if that is what it freaking takes.

**To Reproduce**
Turn on dev mode in phone
Allow installing unsigned apks
Download winlator 7.1
Install winlator and ignore warnings
Create Winlator Container and set both x86 and x64 boxes to run in compatibility mode
Assign D drive in winlator to a folder you have access to on your phone
Put Pkhex and .NET Desktop 8.0.5 in that folder (Note it is NOT the first version on the downloads page if you google it)
Run winlator container
Open Wine settings and set it to run in Windows 10 mode not Win7
Run .NET installer from D Drive
Run Pkhex
It crashes

Considering it is running in "Windows" and has the necessary dependencies installed I was wondering if you let me know what I'm missing to get Pkhex working. Otherwise I'll be stuck building houses in the heat for a month with no Alakazams

**Crash log**
System.ComponentModel.Win32Exception (0x80004005): Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.ComboBox.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.IHandle<Windows.Win32.Foundation.HWND>.get_Handle()
   at Windows.Win32.PInvoke.SendMessage[T](T hWnd, MessageId Msg, WPARAM wParam, LPARAM lParam)
   at System.Windows.Forms.ComboBox.UpdateItemHeight()
   at PKHeX.WinForms.Controls.PKMEditor..ctor()
   at PKHeX.WinForms.Main.InitializeComponent()
   at PKHeX.WinForms.Main..ctor()
   at PKHeX.WinForms.Program.Main()
System.ComponentModel.Win32Exception (0x80004005): Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.IHandle<Windows.Win32.Foundation.HWND>.get_Handle()
   at Windows.Win32.PInvoke.GetWindowLong[T](T hWnd, WINDOW_LONG_PTR_INDEX nIndex)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at PKHeX.WinForms.ErrorWindow.ShowErrorDialog(String friendlyMessage, Exception ex, Boolean allowContinue)
   at PKHeX.WinForms.Program.CurrentDomain_UnhandledException(Object sender, UnhandledExceptionEventArgs e)

**Comment by Masamune3210** [comment]
Something in the emulation of Windows is incorrect in one way or another and its preventing pkhex from creating its initial window handle, aka, the app is asking windows to make a window for it, windows is either refusing or not complying correctly, and pkhex is immediately crashing and burning because you kind of need a window to be able to proceed.


Long story short, Wine isn't going to work in its current set up. Going to have to either figure out how to get Wine to behave or find another means of attacking the problem

**Comment by Wolf-lbh** [comment]
> Something in the emulation of Windows is incorrect in one way or another and its preventing pkhex from creating its initial window handle, aka, the app is asking windows to make a window for it, windows is either refusing or not complying correctly, and pkhex is immediately crashing and burning because you kind of need a window to be able to proceed.
> 
> Long story short, Wine isn't going to work in its current set up. Going to have to either figure out how to get Wine to behave or find another means of attacking the problem

Thanks for the advice but I think I've reached the limit of what I can figure out how to do in the stripped down Winlator version of Wine. Maybe I'll try again later but I've made my way through about 15 different failure points to get to where I'm at and I'm feeling pretty done.

**Comment by Masamune3210** [comment]
No shame in that. Close the issue if you are done with it, if you wouldn't mind
