### ISSUE TITLE
Move editing bug? (Might be on my end)

### ISSUE THREAD

**Issue by DaWoblefet** [kwsch/PKHeX#468]
Got this while editing a Smeargle's moveset in a Moon save. I was genning a bunch of Smeargle to test things in-game, had no problems with the other ones.

Exception Details:
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Windows.Forms.CurrencyManager.Find(PropertyDescriptor property, Object key, Boolean keepIndex)
   at System.Windows.Forms.ListControl.set_SelectedValue(Object value)
   at PKHeX.Main.updateLegality(LegalityAnalysis la, Boolean skipMoveRepop)
   at PKHeX.Main.clickMoves(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.GroupBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\dawob\Documents\PKHeX (11-17-16)\PKHeX.exe

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by kwsch** [comment]
Could you supply a PKM file to help replicate?
What generation (SAV6/SAV7)?

**Comment by DaWoblefet** [comment]
SAV7. For context, I was editing in a bunch of Smeargle with different moves for mechanics testing. I can't seem to replicate the error message again, though. Simply closing and reopening PKHeX let me continue working as normal.
[235 - Smeargle - 11C364271E8D.zip](https://github.com/kwsch/PKHeX/files/612221/235.-.Smeargle.-.11C364271E8D.zip)

**Comment by kwsch** [comment]
Could be possible that the issue was fixed in the past few days. I'll close this but if you're able to reproduce the error feel free to reply here with the following:

Build used (link to commit / etc)
Steps taken to reproduce (starting from opening the program).

May be useful to have the '.pdb' file in the same folder for linenumber error reporting; usually can only get that if you've compiled it yourself.
