### ISSUE TITLE
Error when loading .pk7 with Gen 3 or 4 origin

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#954]
Tested with latest commit, full errors listed below.

Gen 3: http://pastebin.com/T3zfgD2a
Gen 4: http://pastebin.com/XUHrKqF2

[Here](https://github.com/kwsch/PKHeX/files/856257/pkm.zip) are the `.pk7` files if you need them.

Edit: this does not happen with Gen 1/5/6/7; only 3/4.

**Comment by PrometheusG** [comment]
Same problem-error message but with all generations, except Gen1

One exception to the above:
Gen 5 loads but an unhandled exception occurs:
Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PKHeX.Core.Legal.<>c__DisplayClass171_0.<getTutorMoves>b__7(Int32 t) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX\Legality\Core.cs:line 2273
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at PKHeX.Core.Legal.getTutorMoves(PKM pkm, Int32 species, Int32 form, Boolean specialTutors, Int32 generation) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX\Legality\Core.cs:line 2273
   at PKHeX.Core.Legal.getMoves(PKM pkm, Int32 species, Int32 lvl, Int32 form, Boolean moveTutor, GameVersion Version, Boolean LVL, Boolean specialTutors, Boolean Machine, Boolean MoveReminder, Int32 Generation) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX\Legality\Core.cs:line 2100
   at PKHeX.Core.Legal.getValidMoves(PKM pkm, GameVersion Version, DexLevel[] vs, Int32 Generation, Boolean LVL, Boolean Relearn, Boolean Tutor, Boolean Machine, Boolean MoveReminder) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX\Legality\Core.cs:line 1935
   at PKHeX.Core.Legal.getValidMoves(PKM pkm, GameVersion Version, IReadOnlyList`1 vs, Boolean LVL, Boolean Relearn, Boolean Tutor, Boolean Machine, Boolean MoveReminder) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX\Legality\Core.cs:line 1911
   at PKHeX.Core.LegalityAnalysis.getSuggestedMoves(Boolean tm, Boolean tutor, Boolean reminder) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX\Legality\Analysis.cs:line 306
   at PKHeX.Core.LegalityAnalysis..ctor(PKM pk) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX\Legality\Analysis.cs:line 79
   at PKHeX.WinForms.PKMUtil.getSprite(PKM pkm, SaveFile SAV, Int32 box, Int32 slot, Boolean flagIllegal) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX.WinForms\Util\PKMUtil.cs:line 110
   at PKHeX.WinForms.Main.getSlotFiller(Int32 offset, PictureBox pb) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX.WinForms\MainWindow\Main.cs:line 3903
   at PKHeX.WinForms.Main.setPKXBoxes() in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX.WinForms\MainWindow\Main.cs:line 3768
   at PKHeX.WinForms.Main.getBox(Object sender, EventArgs e) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX.WinForms\MainWindow\Main.cs:line 3926
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at PKHeX.WinForms.Main.clickBoxRight(Object sender, EventArgs e) in C:\BuildAgent\work\3a4b40ceb1c3e268\PKHeX.WinForms\MainWindow\Main.cs:line 3313
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.2307, Culture=neutral, PublicKeyToken=null
C:\Users\Γιώργος\Desktop\PKHeX Build 2307 (1)\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.2307, Culture=neutral, PublicKeyToken=null
C:\Users\Γιώργος\Desktop\PKHeX Build 2307 (1)\PKHeX.Core.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=el, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_el_b77a5c561934e089\System.Windows.Forms.resources.dll

mscorlib.resources, Version=4.0.0.0, Culture=el, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_el_b77a5c561934e089\mscorlib.resources.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
